- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/arm7tdmi.rs
- ARM: Add test for `Branch` instruction
- CI: Run `test` instead of `build`
> ARM: Introduce tests

- src/arm7tdmi.rs
MOV implementation with related test.
> ARM now can execute a MOV immediate instruction with S = 0

- src/arm7tdmi.rs
- Implement MOV (immediate) for ARM mode
- Add test for MOV Rx,x instruction
- ARM: Make conversion `u32` -> `ArmInstruction` more idiomatic
> Make converstion from `u32` to `ArmModeInstruction` idiomatic

- .github/workflows/rust.yml
> CI: Add fmt check before test

- Cargo.lock
- Cargo.toml
- src/arm7tdmi.rs
- src/egui_app.rs
- src/main.rs
- src/ppu.rs
This allow us to create an empty GUI but running in loop the cycles of the CPU, then can be a good start to think a good UI and probably start to print something like the buffer in PPU.
> UI: Sketch firt implementation of GUI for `clementine`

- src/arm7tdmi.rs
- src/cpsr.rs
- src/instruction.rs
Signed-off-by: Federico Bruzzone <federico.bruzzone.i@gmail.com>
> Make conversion from `hex` to `bin`

- src/cartridge_header.rs
- src/main.rs
> Move checksum validation into its function

- src/arm7tdmi.rs
- src/condition.rs
- src/cpsr.rs
Closes #8 
P.N.
The only part missing is `saved_program_status_register (SPSR_<mode>)` of the CPSR
Sign-off-by: Federico Bruzzone <federico.bruzzone.i@gmail.com>
> CPSR: Add all `ARM condition filed` and finished `CPSR`

- src/arm7tdmi.rs
Since the shift operation is used by several instructions, I preferred to separate it from `Data Processing (ALU)`.
I made two methods, `shift` and `shift_immediate`, the first one performs special operations in case the `shift_amount` is `0`, the second one performs the shift operation directly.
> Refactor shift operation

- src/arm7tdmi.rs
> ARM: Implemente TEQ when S=0

- src/arm7tdmi.rs
> ARM: Implement `ADD` for ALU

- src/alu_instruction.rs
- src/arm7tdmi.rs
- src/opcode.rs
Closes #70 
Signed-off-by: Federico Bruzzone <federico.bruzzone.i@gmail.com>
> Fix inconsistency in the variable name

- src/arm7tdmi.rs
Straightforward implementation of the CMP instruction. Based on the previous implementation of TEQ. More test should be written.
PS: This is the second PR on this topic, I made a mistake and closed the previous PR https://github.com/RIP-Comm/clementine/pull/68
PPS: Yes, this is the third PR on this topic. I made the same mistake twice...
> ARM: Implement `CMP`ALU Instruction 

- .github/workflows/rust.yml
> CI: Update trigger path with new workspaces directories

- emu/src/arm7tdmi.rs
- emu/src/instruction.rs
- emu/src/opcode.rs
This is the first implementation of LDM for a specific case encountered,
we need to improve our test suite for covering more cases.
Co-authored-by: Alessio Cosenza <cosenzaalessio17@gmail.com>
> ARM: Implement Block Data Transfer (LDM)

- emu/src/arm7tdmi.rs
This mainly fixes the behavior when using `PC` as an operand in ALU ops.
From documentation:
> The PC value will be the address of the instruction, plus 8 or 12 bytes due to instruction prefetching. If the shift amount is specified in the instruction, the PC will be 8 bytes ahead. If a register is used to specify the shift amount the PC will be 12 bytes ahead
I'm not 100% sure whether the +12 offset has to be used when `PC` is used as the first operand (no shift involved with it). But since the documentation doesn't specify I assume the same logic applies to both the first and second operands. This is confirmed by GBATEK.
This PR also adds a check when the value read from the shift register is 0. In this case, the documentation specifies that the value in `Rm` has to be used as is, …
> Fix `PC` usage in ALU ops and fix one shift register case

- emu/src/internal_memory.rs
> Add Palette and VRAM

- .github/workflows/rust.yml
- justfile
> CI: Use just in CI

- emu/src/internal_memory.rs
> Fix memory buffers in `InternalMemory`

- emu/src/internal_memory.rs
> Memory: Add bios memory

- emu/src/arm7tdmi.rs
After executing an instruction that modifies `PC`, it should not be advanced by `4`.
I've added that functions that implement instructions should return a `bool` representing whether `PC` should be increased after its execution.
I don't know if this is the best solution, maybe we could use an `Option<u32>` containing the new `PC` (returned from the instruction function) if `Some` or execute `advance_program_counter` if `None`. We can discuss it here :) 
Tests are broken since they were written taking into account the fact that `PC` is always increased, when we decide which way to take I can fix the tests
> ARM: Add check before advancing `PC`

- Cargo.toml
- emu/Cargo.toml
- emu/src/arm7tdmi.rs
- emu/src/bitwise.rs
- emu/src/lib.rs
- emu/src/memory/internal_memory.rs
- emu/src/ppu.rs
- emu/src/render/mod.rs
- emu/src/render/palette_color.rs
- emu/src/single_data_transfer.rs
- justfile
- src/main.rs
- ui/Cargo.toml
- ui/src/dashboard.rs
- ui/src/lib.rs
- ui/src/palette_visualizer.rs
Closes #89 
I also added a feature  _"debug"_ to put random values in the `palette_ram`. In can be useful to use this features also to some hard coded test for the render process.
To run clementine in debug mode you just need to run the command:
`just debug *rom_path/rom.gba*`
> Palette visualizer

- emu/src/arm7tdmi.rs
I've fixed an issue with the `Branch` op since it was not sign extending the offset, so it would not have worked with negative offsets.
I also took it as an opportunity to refactor it a bit: now there's only 1 branch function instead of `branch` and `branch_and_link` that do the same thing. I've also united the tests into a single test function
> ARM: Refactor `Branch`/`BranchLink` ops

- emu/src/arm7tdmi.rs
- emu/src/memory/internal_memory.rs
- Memory: Add unused chunk of memory
- ARM: Add LDR in block data transfer
> Block data transfer LDR

- .github/workflows/rust.yml
> CI: Run test over macos and windows

- emu/src/memory/internal_memory.rs
- emu/src/single_data_transfer.rs
- src/main.rs
- ui/src/cpu_inspector.rs
- Memory: Add unused memory as map
- Everywhere: Fix lint after bumping rust version
- ARM: Implement single data transfer LDR with WORD
> single data transfer ldr word

- emu/src/memory/internal_memory.rs
- emu/src/single_data_transfer.rs
- ARM: Implement single data transfer STR with WORD
- Memory: Add another region of unused memory
> Single data transfer STR WORD

- emu/src/arm7tdmi.rs
- emu/src/gba.rs
- emu/src/render/ppu.rs
- emu/src/single_data_transfer.rs
- ui/src/cpu_inspector.rs
- ui/src/dashboard.rs
- ui/src/gba_display.rs
Implements `Play` button in UI.
Since UI is in a different thread everything had to be moved from `Rc<RefCell<>>` to `Arc<Mutex<>>`.
I guess there's a lot that could be improved, it's my first time working with threads in rust :D
I opted for `.unwrap()` after `.lock()` instead of `if let Ok(...) = ...lock()` because I think it's better to have panics for now instead of "silent failures"
> Play button

- emu/src/arm7tdmi.rs
> ARM: Implement Halfword data transfer immediate offset

- CONTRIBUTING.md
- extra/pre-commit
Added `pre-commit` git hook and instructions on how to activate it.
I decided to not use `just` in the pre-commit hook since it may be that developers not use it.
> Add pre-commit hook

- emu/src/arm/arm7tdmi.rs
- emu/src/arm/data_processing.rs
- emu/src/arm/psr.rs
This PR adds support for the `PSR` kind instructions.
> ARM: Add `PSR transfer` instruction

- emu/src/arm/arm7tdmi.rs
I know there are part of the code duplicated from "immediate offset" but
until all condition are implemented I prefer to keep separated in order
to see all differences of those instruction.
> ARM: Implement data transfer register offset

- emu/src/arm/arm7tdmi.rs
- emu/src/memory/internal_memory.rs
This PR should be merged after #124
> Add chunk of unused memory

- emu/src/arm/arm7tdmi.rs
- emu/src/arm/data_processing.rs
- emu/src/arm/single_data_transfer.rs
> Use constant with good name for refering to PC

- emu/src/arm/arm7tdmi.rs
- emu/src/arm/single_data_transfer.rs
> ARM: Refactor up/down bit into a reaadable enum

- emu/src/memory/internal_memory.rs
- emu/src/memory/interrupts.rs
- emu/src/memory/mod.rs
- Memory: Refactor lcd as IoDevice
- Memory: Add struct for read/write interrupts area
> Add interrupts memory region

- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/data_processing.rs
- emu/src/cpu/mod.rs
- emu/src/cpu/move_compare_add_sub.rs
- emu/src/cpu/opcode.rs
> THUMB: Implement mov/cmp/add/sub

- emu/src/cpu/arm7tdmi.rs
> Thumb: Implement pc-relative load

- emu/src/cpu/arm7tdmi.rs
- extra/pre-commit
> Thumb: Fix the value used to set relative load

- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/data_processing.rs
- emu/src/cpu/flags.rs
- emu/src/cpu/opcode.rs
* Add `OperandKind` struct to encode immediate/register
* Implement `AddSubtract` and `CondBranch` instructions
> THUMB: `CondBranch` and `AddSubtract` instructions

- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/opcode.rs
- emu/src/memory/internal_memory.rs
- emu/src/render/ppu.rs
- ui/src/dashboard.rs
- Thumb: Implement partially Push/Pop
- Everwhere: Fix lint after bump rust to 1.66
> Partially implementation of Push/Pop

- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/opcode.rs
> THUMB: Implement `AddOffsetSP`

- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/opcode.rs
> THUMB: Implement `SpRelativeLoadStore`

- emu/src/cpu/alu_instruction.rs
- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/data_processing.rs
- emu/src/cpu/opcode.rs
- Thumb: Add alu operation
- Thumb: Implement `mvn` for ALU
> Alu operations

- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/opcode.rs
- Thumb: Add alu operation
- Thumb: Implement `mvn` for ALU
- Thumb: Implement `Long Branch Link`
> Implement Long Branch Link

- emu/src/cpu/alu_instruction.rs
- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/data_processing.rs
> Thumb: Implement `tst`

- emu/src/bitwise.rs
- emu/src/cpu/alu_instruction.rs
- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/data_processing.rs
- emu/src/cpu/opcode.rs
Thumb: Partial implementation of `LoadStoreImmOffset`
CPU: Move into generic shift function `ASR`
Thumb: Implement `uncond_branch`
Thumb: Implement `orr`
> Progress on executing full BIOS

- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/data_processing.rs
> Thumb: Implement `mul` for ALU

- emu/src/cpu/arm7tdmi.rs
* Refactored HalfWord LoadStore Register/Immediate offset into a single function.
* Implemented all cases
> THUMB: Refactor and finish `HalfWord Load/Store`

- emu/src/cpu/data_processing.rs
- emu/src/cpu/instruction.rs
* Adding `R` char in second op data processing ASM
* Fixing asm when shift amount is 0
* Readded some tests deleted in the last PR
> Fix dataprocessing asm

- emu/src/cpu/arm7tdmi.rs
We were not sign extending the offset correctly
> THUMB: Fix `UncondBranch`

- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/instruction.rs
- emu/src/cpu/opcode.rs
> Thumb: Implement load_address

- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/condition.rs
- emu/src/cpu/flags.rs
- emu/src/cpu/instruction.rs
- emu/src/cpu/move_compare_add_sub.rs
- emu/src/cpu/opcode.rs
- emu/src/cpu/psr.rs
- emu/src/cpu/single_data_transfer.rs
> Arm: Add ASM of coprocessor data transfer

- emu/src/cpu/arm/alu_instruction.rs
- emu/src/cpu/arm/operations.rs
- emu/src/cpu/thumb/instruction.rs
- emu/src/cpu/thumb/operations.rs
- emu/src/memory/internal_memory.rs
> Implement more ALU operation

- emu/src/cpu/arm/instructions.rs
- emu/src/cpu/arm/mode.rs
- emu/src/cpu/arm/operations.rs
- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/flags.rs
Left to do:
- Add tests for the disassembler string
> Halfwordtransfer asm

- emu/src/bus.rs
- emu/src/cpu/arm/operations.rs
- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/thumb/operations.rs
- emu/src/gba.rs
- emu/src/lib.rs
- ui/src/cpu_handler.rs
> Implementation of cycles

- emu/src/cpu/arm/instructions.rs
> Arm: Fix decoding of Multiply/MultiplyLong

- emu/src/bus.rs
- emu/src/cpu/arm/operations.rs
- emu/src/cpu/thumb/operations.rs
- emu/src/memory/internal_memory.rs
- LCD: Draft implementation of `step`
- Thumb: Implement `cmn`
- Thumb: Implement `bic`
> Progress for LCD bitmap mode in Thumb

- emu/src/bus.rs
- emu/src/cpu/arm/operations.rs
- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/hardware/lcd.rs
First implementation of exceptions.
Draft since nothing fires an interrupt yet so I don't know if it works :D
> Handle exceptions

- emu/src/cpu/arm/operations.rs
- emu/src/cpu/arm7tdmi.rs
- emu/src/cpu/hardware/lcd.rs
- emu/src/cpu/hardware/lcd/object_attributes.rs
- emu/src/cpu/hardware/lcd/point.rs
- emu/src/cpu/thumb/operations.rs
- ui/src/app.rs
- LCD: Start work on rendering sprites
- ALU: Fix `carry` calculation
- Thumb: Implement `Lsr` alu operation
- UI: Show by default the gba display
- Thumb: Implement LSL
- Better name for tests
- ARM: Implement Software Interrupt
> Display logo and exit from BIOS
