src/condition.rs, src/cpsr.rs, src/cpu.rs, src/main.rs
- CPU: Decode condition of opcode instruction
- Rename to `Cpu`
- Rename to `Cpsr`
Now our CPU can decode the condition of the current opcode
and decide if it should execute the isnstruction.
=> Implement decode condition of the instruction

src/arm7tdmi.rs
=> CPU: Improve conversion from `Vec<u8>` to `u32`

src/arm7tdmi.rs, src/cpu.rs
Now our CPU recognize if instruction is `Branch` or `BranchLink`.
Co-authored-by: Davide Gallotti <d.gallotti@outlook.it>
Co-authored-by: Alessandro Grassi <alessandrograssi17@gmail.com>
=> CPU: Decode `Branch` instruction

src/cartridge_header.rs
If checksum is invalid 'clementine' stops working.
=> Cartridge: Verify checksum of the ROM loaded.

.gitignore, src/cartridge_header.rs, src/main.rs
Refactor of the struct.
Now supports headers: entry_point, nintendo_logo, game title, and game code.
I did not implement all the headers in order to leave room for a issue for newcomers.
=> Cartridge: Improve `CartridgeHeader` with new fields

.github/workflows/rust.yml
In this way we can save lot of resources.
=> CI: Don't trigger GitHub Action on docs changes

src/arm7tdmi.rs
Before this change, code checked only the bit set to 1.
It will be added a verification for every significant bit in the opcode.
=> Improve check instruction with specific mask for every opcode

src/alu_instruction.rs, src/arm7tdmi.rs, src/cpsr.rs, src/instruction.rs, src/main.rs
I implemented [this](https://rust-console.github.io/gbatek-gbaonly/#--arm-opcodes-data-processing-alu) (the chunk with ">" on the left)
```
Bit    Expl.
31-28  Condition
27-26  Must be 00b for this instruction
25     I - Immediate 2nd Operand Flag (0=Register, 1=Immediate)
24-21  Opcode (0-Fh)               ;*=Arithmetic, otherwise Logical
0: AND{cond}{S} Rd,Rn,Op2    ;AND logical       Rd = Rn AND Op2
1: EOR{cond}{S} Rd,Rn,Op2    ;XOR logical       Rd = Rn XOR Op2
2: SUB{cond}{S} Rd,Rn,Op2 ;* ;subtract          Rd = Rn-Op2
3: RSB{cond}{S} Rd,Rn,Op2 ;* ;subtract reversed Rd = Op2-Rn
4: ADD{cond}{S} Rd,Rn,Op2 ;* ;add               Rd = Rn+Op2
5: ADC{cond}{S} Rd,Rn,Op2 ;* ;add with carry    Rd = Rn+Op2+Cy
6: SBC{cond}{S} Rd,Rn,Op2 ;* ;sub with carry    Rd = Rn-Op2+Cy-1
7: RSC{cond}{S} …
```
=> Add Data Processing (ALU) Core

.gitattributes, src/cartridge_header.rs
All the cartridge header implementations have been added to the `cartridge_headers.rs` file. (#17) 
Keep in mind:
`1.` BIOS must be able to overwrite the boot_mode header, as defined in the extract_boot_mode function comments; 
`2.` BIOS must be able to overwrite the slave_id_number header, as defined in the extract_slave_id_number function comments; 
`3.` If the GBA has been booted by using Joybus transfer mode, we have to put our initialization procedure directly at joybus_mode_entry_point address, or redirect to the actual boot procedure by depositing a "B <start>" opcode in the space used by joybus_mode_entry_point.
=> cartridge_headers: Add all cartridge headers

src/cartridge_header.rs, src/cpu.rs
Comments aimed at specifying the behaviour of a function should be marked with `///`.
=> Turn comments into docs

Cargo.lock, Cargo.toml, src/bitwise.rs, src/main.rs
It adds some methods to check and set single bits. For now there aren't methods to handle multiple bits masks, and it's limited to u32 (due to the assence of a common Integer trait  in rust).
Refers to #33
=> Add bit manipulation methods

src/cpsr.rs
I wrote a test for `0xAAAA` representation and another for `0xAAAAAAAA` representation.
All those made with `0xAAAA` fail and those with `0xAAAAAAAA`.
P.N.
I used the hex notation for the condition to make the error more explicit. I will convert it to binary.
Signed-off-by: Federico Bruzzone <federico.bruzzone.i@gmail.com>
=> CPSR: Add tests for `sign_flag` and `overflow_flag`

src/arm7tdmi.rs, src/bitwise.rs, src/cpsr.rs
This don't cover all case because we are not taking care of changing all CPU register and other marginal stuff,
but it's a start :).
=> ARM: Implement `teq` `ALU` instruction

.github/workflows/rust.yml, src/alu_instruction.rs, src/arm7tdmi.rs, src/bitwise.rs, src/cartridge_header.rs, src/condition.rs, src/cpsr.rs, src/cpu.rs, src/egui_app.rs, src/instruction.rs, src/ppu.rs
In the near future we can shortcut this long command with `make` or `just`.
Another improvements is enable all warnings, but is a long run :)
=> CI: Enable more pedantic warnings on clippy

src/arm7tdmi.rs, src/instruction.rs
Now we have one of the all combination of usage of a `DataTrasfer`, I also
introduce a new enum for redability of data transfer operation, in case
implemented here it is `Ldr`.
=> ARM: Implement `TransImm9` a DataTransfer case

src/arm7tdmi.rs
Closes #46 
It is a first implementation.
This implementation looks like that of `branch`, but if the bit 24 is set to 1 we need save the PC in cell 14 of the `registers`.
Signed-off-by: Federico Bruzzone <federico.bruzzone.i@gmail.com>
=> ARM: Add `branch_link` implementation  for `arm7tdmi`

src/arm7tdmi.rs
=> ARM: `TEQ` instruction uses value on register[rn]

src/alu_instruction.rs, src/arm7tdmi.rs, src/bitwise.rs
Implement the `get_bits` method that takes as input a RangeInclusive<u8>. 
Unfortunately, in Rust it is only possible to make ranges in ascending order, the opposite of the formatting used in the documentation. However, I think it still can greatly increase the readability of the codebase.
=> Add `get_bits` method for `u32`

src/arm7tdmi.rs, src/condition.rs
Before of this PC was a separated variable, in original design PC is only
R15 of array of registers.
Right now in `check_mov_rx_immediate` we verify immediate value from 0 to 15, is this a realistic situation?
Another question, we are advancing PC after `execution`, does this make sense?
We can also skip those question right now, just some thoughts for future work :)
=> ARM: Implement PC within same bank of 16 register for CPU

src/arm7tdmi.rs, src/internal_memory.rs, src/io_device.rs, src/main.rs
- Memory: Add trait for generic read/write operation
- Now it is enough simple, without returning result or no byte/word distinction.
Probably in future we need more specific function but let's start simple.
- Memory: Add `Internal Memory` struct
- Here I just preparad interal "ram" but we can change the struct name in future based on how we want the granularity of our struct.
- ARM: Add memory field into arm implementation of CPU
- This allows to fix `SingleDataTransfer::Ldr` istruction.
=> Implement first simple version of memory

src/arm7tdmi.rs, src/condition.rs, src/cpsr.rs, src/cpu.rs, src/instruction.rs, src/main.rs, src/opcode.rs
I think using `u32` to handle opcodes has become frustrating and confusing. Therefore, I created a structure that can handle the main functions of the opcode: 
- Condition
- Instruction
- Bits Manipulation
- Debug/Display
Unfortunately, the `Display` support for `Single Data Transfer` is missing since currently `ArmModeInstruction::DataTransfer` is used to represent multiple instructions at once. Therefore, it is necessary to divide `DataTransfer` in a manner similar 
to `DataProcessing` (1, 2, and 3). BTW, If you do not use the `Display` trait of `Opcode` in `Arm7tdmi::decode()` everything works as before.
=> Add `Opcode` struct

emu/src/arm7tdmi.rs, emu/src/cpsr.rs
This PR adds support for `ORR` instruction and changes `ADD` behavior in some cases.
In the `data_processing` function, when the immediate bit was 0, `op2` was being set to the `[3:0]` value, instead of reading the value from the register. I think this was because the `shift` function was intended to read this value from the register, but right now it's not happening in every case (only when `shift_amount == 0` and `shift_type == 1 or 2`). And to me, the `shift` function should not have the responsibility to read from the register, in any case.
The same thing was happening in the `ADD`: the `Rn` operand was being directly used as value in the operation, instead of reading it from the register. I've also added `CPSR` bits output to the `ADD` instruction.
This PR probably breaks the `shift` …
=> `ORR` and some `ADD` fixes

emu/src/alu_instruction.rs, emu/src/arm7tdmi.rs
I've refactored a bit and completed the shift op2 logic.
* Added `Type` trait for ALU instructions to know if it is logical or arithmetical
* I moved the `get_operand` logic to a separate function
* I refactored a bit the `shift` logic: now barrel shifter operations correctly set the carry flag when the instruction is logical and `S` is set
I know that `09a20b5b9f95fbc6f301b13b321c79b194b1f9f7` is big but it doesn't make sense to me to split it, since it's all about the same task, but let me know :)
I think the barrel shifter logic is complex enough to be worth quite some tests. I didn't have time yet to add them but they're for sure needed.
=> Refactor shift operand

emu/src/arm7tdmi.rs, emu/src/bitwise.rs, emu/src/internal_memory.rs, emu/src/io_registers.rs, emu/src/lib.rs
This PR adds `LCDRegisters` memory region to `InternalMemory`. It serves as preparation to implement the ppu (hopefully :D).
Structs `IORegister` and `LCDRegisters` have been written to model these registers.
Unit tests have been added to `InternalMemory`.
Added `get_byte` and `set_byte` in `Bits` trait to selectively read/write a specific byte from an `u32`.
=> Adding `LCDRegisters` mapping to `InternalMemory`

emu/src/arm7tdmi.rs
This PR adds the missing logical ops in ALU: `AND`, `EOR`, `TST`, `BIC`, `MVN`.
=> ARM(ALU): Added missing logical ops

emu/src/arm7tdmi.rs, emu/src/cpsr.rs
* Add support for `SUB`, `RSB` and `CMN` ALU op
* Fix the `CMP` op: it was not executing all the sub logic (overflow/carry check, etc.)
* Fix `MOV` op: it was not setting the `CPSR` flags
* Extracted the add and sub logic to two separate functions since they are used in many operations (`SUB` and `CMP`, `ADD` and `CMN`) and there will be more with the same logic: `ADC`, `SBC`, `RSC`. I created a new struct to return the result of an arithmetic operation.
=> ALU: Add `SUB`, `RSB`, `CMN` op and Fix `CMP`, `MOV` op

emu/src/bitwise.rs, emu/src/memory/lcd_registers.rs
Documented here: [DISPCNT - LCD Control](https://rust-console.github.io/gbatek-gbaonly/#--lcd-io-display-control).
=> Get info from `DISPCNT` register in LCD registers

emu/src/arm7tdmi.rs, emu/src/opcode.rs
* When the instruction can't be executed because of cond flags, the program counter should be increased instead of staying on the same instruction forever
* When printing the instruction, we should pad with leading zeroes otherwise it would not print 32 bits when `cond` starts with 0.
=> Fix advance cond

emu/src/arm7tdmi.rs, emu/src/single_data_transfer.rs
* Now correctly adds `12` when storing `R15 (PC)`
* Inverts iteration order when using decrementing. From documentation:
> The lowest register also gets transferred to/from the lowest memory address
So we should invert the order when decrementing otherwise we would store/save in inverse order.
=> Fix block data transfer

Cargo.lock, Cargo.toml, emu/Cargo.toml, emu/src/arm7tdmi.rs, emu/src/instruction.rs, logger/Cargo.toml, logger/src/lib.rs, src/main.rs, ui/Cargo.toml, ui/src/dashboard.rs
- Logger: Add new logger for `clementine`
- Everywhere: Use logger in the code with a special arg `--log-on-file`
Basically the feature is because I would love to analyze the data and istruction post-run of a specific ROM, since now we have enough instruction running but we don't know where are bugs :).
This allow us to log on stdout as befor of log on a file saved under `/tmp/clementine-{utc::now()}.log` with a special arg like `./clementine --log-on-file my_game.gba`.
We need to check this path on windows platform.
=> Add new logger

emu/src/arm7tdmi.rs, emu/src/data_processing.rs, emu/src/instruction.rs, emu/src/opcode.rs, emu/src/single_data_transfer.rs, src/main.rs
Aligned all instruction with the document of proper CPU. Many of those
are not implemented, neither displayed well in formatted log, but now we
have all istruction decode well (I hope :')).
Now is more easy to understand which bits should be true/false, using
mask were not so easy to understand from the log.
The decode function is ordered on how many bit are already know as
invariant.
=> ARM: Improve decode instruction from op_code (u32)

emu/src/arm/arm7tdmi.rs, emu/src/arm/condition.rs, emu/src/arm/cpu_modes.rs, emu/src/arm/mod.rs, emu/src/arm/psr.rs, emu/src/arm/register_bank.rs
* Refactored `Cpsr` to `Psr` to use the same struct for both `cpsr` and `spsr`
* Added `RegisterBank` struct into `Armv7tdmi`. This struct stores the banked registers. Banked general purpose registers (R8-R14 for `fiq` and R13-R14 for `supervisor`, `abort`, `irq`, and `undefined`) are mapped to general purpose registers when in the given mode. For example: when in mode `fiq` if the CPU accesses R13, it's using the `r13_fiq`. For this reason, I've added `bank_registers` to save banked registers depending on the current mode and `restore_registers` to restore from the bank.
This work is preliminary to implementing `PSR` instructions and to fix all the instructions already implemented to take into account spsr registers in some specific cases
I'm not 100% sure the idea I came up with the …
=> `spsr` and register bank

emu/src/memory/internal_memory.rs
=> Memory: Use heap allocated vec instead of fixed size array on stack

emu/src/gba.rs, emu/src/memory/internal_memory.rs, ui/src/dashboard.rs
We will probably need to add a flag for loading using specific path.
=> GBA: Read bios binary from `current_dir` location

emu/src/arm/arm7tdmi.rs, emu/src/arm/single_data_transfer.rs, emu/src/gba.rs, emu/src/memory/internal_memory.rs, ui/src/dashboard.rs
- Memory: Use for address `usize` type
This because in most of place is more convenient keep conversion outside the memory functions.
- CPU+Memory: Move rom data into memory
Now rom data is mapped into memory struct, that's because PC starts from 0 and read/write from bios.
This means that now we need bios for start a game.
=> ROM in Memory

emu/src/arm/arm7tdmi.rs, emu/src/arm/data_processing.rs, emu/src/arm/single_data_transfer.rs
This should be merged after #129 .
* Fix a bug in `single_data_transfer` function: we were inverting the logic of the up/down bit
* Now cpu boots in supervisor mode (https://www.reddit.com/r/EmuDev/comments/6tr4fz/gba_does_anyone_have_any_information_on_the/ and https://www.cs.rit.edu/~tjh8300/CowBite/CowBiteSpec.htm#SVC). Not 100% sure yet but I think it's still better than booting in User mode :D
=> Single data transfer fix

emu/src/memory/internal_memory.rs, emu/src/memory/timer_registers.rs
Now timer implement trait `IoDevice`, this allow bettere redability and
maybe a future possible mock or implemetation :)
=> Memory: Refactor timer as IO device

emu/src/arm/arm7tdmi.rs, emu/src/arm/data_processing.rs, emu/src/arm/psr.rs, emu/src/arm/single_data_transfer.rs, emu/src/memory/internal_memory.rs, emu/src/memory/interrupts.rs, emu/src/memory/mod.rs
To be merged after #134 .
This PR mainly reverts the increment after fetch commit.
I also changed the `MSR` instruction to use `set_mode_raw`, directly setting the mode bits, this is because the BIOS wants to execute:
And it was failing since it was trying to do `set_mode(Mode::try_from(0b00000).unwrap())` (`0b00000` is not a mode). But if the BIOS wants to do it we should let it do :D
I've also added a panic in the `branch_and_exchange` as we don't have the THUMB mode yet, thus every instruction executed after the `branch_and_exchanged` is meaningless (the bios was looping).
=> Revert increment after fetch + small fixes

.github/workflows/rust.yml
Adding test codecoverage in CI.
I haven't used the `cargo-tarpaulin` action since it was failing:
=> CI: Add test coverage

emu/src/arm/arm7tdmi.rs, emu/src/arm/data_processing.rs, emu/src/arm/instruction.rs, emu/src/arm/opcode.rs, emu/src/arm/psr.rs
* `CpuState` was using the inverted logic
* `BX` was not reading the value from `Rn`
* Added instruction decode for THUMB mode
* Setting lsb in PC to 0 before fetching
=> Small fixes in thumb/bx

emu/src/bitwise.rs, emu/src/cpu/arm7tdmi.rs, emu/src/cpu/flags.rs, emu/src/cpu/mod.rs, emu/src/cpu/opcode.rs, emu/src/cpu/single_data_transfer.rs, emu/src/memory/internal_memory.rs
* Add `write_word` function to internal memory
* Implement instruction
* Rewrote `get_bits` in order to avoid using `for` and using binary arithmetics instead. It's faster than 50% on `u32` (but this 50% is only 20ns, lol).
Should we move `ReadWriteKind` somewhere else since it's not used only by `single_data_transfer`?
=> THUMB: Implement `Load/Store Register offset` instruction

emu/src/cpu/arm7tdmi.rs, emu/src/cpu/data_processing.rs, emu/src/cpu/register_bank.rs
Merge after #146 
* Fix mode swapping and register bank logic
Before, we were using the different SPSR_{mode} as saved versions
of CPSR. This is wrong, the correct way of doing is that every mode
(except System and User) have their SPSR, separate from the CPSR.
So, the SPSR is just another register (analogous to the CPSR) that gets
banked for every mode.
Another problem was also that we were not saving/restoring the "base"
r8-14 registers. So for example when going from System to FIQ, FIQ
was replacing r8-14 with its own versions. Then, if the system would
have gone from FIQ to System the old values of r8-14 would have not
been restored.
* ARM: Fix MSR op
Now it correctly stores/restores banked registers.
=> Register Bank fix. Fix MSR op

emu/src/cpu/alu_instruction.rs, emu/src/cpu/arm7tdmi.rs, emu/src/cpu/data_processing.rs, emu/src/cpu/psr.rs
- CPU: Create `ShifKind` for u32/u16 conversion
- CPU: Move `ArithmeticOpResult` into alu_instruction module
- Thumb: Implement `LSL` for shift register
=> Thumb: Implement LSL for shift

emu/src/cpu/arm7tdmi.rs
* We were not reading the value in `Rs` in ALU operations in THUMB mode
* We were not sign-extending the offset in the `BL` operation
Since we're using the sign-exteding feature in many places maybe we should put it somewhere? I've tried implementing in `Bits` but it's a bit of a mess since we would need `TryFrom`/`Into` `128` or something like that and it was not working, maybe I can try again, I tried couple of weeks ago
=> Fix thumb ops

emu/src/cpu/arm7tdmi.rs, emu/src/cpu/instruction.rs, emu/src/cpu/opcode.rs
Should we move `disassemble` function to a trait?
=> THUMB: Add `Load\Store sign-ext halfword`

emu/src/cpu/arm7tdmi.rs, emu/src/cpu/data_processing.rs, emu/src/memory/internal_memory.rs, emu/src/memory/interrupts.rs
* Add `cmp` alu op for thumb
* Fix `tst` alu op for thumb (we were not reading the register value)
* Add a new unused region and a new interrupt register
=> Alu `cmp` for THUMB, Fix `tst` for THUMB, Memory regions

emu/src/cpu/psr.rs
Probably a typo here (`&&` is used instead of `||`) as the comment next to this statement also suggest using an `or`. 
Docs [here](https://rust-console.github.io/gbatek-gbaonly/#saved-program-status-registers-spsr_mode) just for reference.
Side note: we should implement some tests accounting for instructions with conditional execution, this way we can spot these little quirks more efficiently.
=> `PSR`: Wrong LE conditional check

emu/src/cpu/arm7tdmi.rs
Added the Program Counter (`R15`) to the `disassembler` window to help with debugging.
There is an error where the Program Counter disappears after so many steps ...
=> CPU: Add program_counter to disassembler

Cargo.lock, Cargo.toml, emu/Cargo.toml, emu/src/cpu/arm7tdmi.rs, vecfixed/Cargo.toml, vecfixed/benches/vector_fixed.rs, vecfixed/src/lib.rs
In this way UI is very fluid, before was very laggy at some point,
because of the string that need to be render for all ASM generated since
time 0. Now I created a little data struct that answer to our need in
order to keep only the last 1k instructions. Seems a reasonable number.
For future improvement we can enable also a possibility to save as file.
=> UI: Use a fixed vector to keep ASM generated

emu/src/cpu/arm/alu_instruction.rs, emu/src/cpu/arm/instructions.rs, emu/src/cpu/arm/mode.rs, emu/src/cpu/arm/operations.rs, emu/src/cpu/arm7tdmi.rs
These two type of instructions do very different
things even if they're under the same opcode
in the datasheet.
Splitting them makes also easier to
manage disassembly for PSR.
=> ARM: Extract `PSRTransfer` instruction from `DataProcessing`

emu/src/cpu/arm/instructions.rs, emu/src/cpu/arm/mode.rs, emu/src/cpu/arm/operations.rs, emu/src/cpu/arm7tdmi.rs, emu/src/cpu/thumb/operations.rs
This PR brings the implementation of the various opcodes for multiplications in arm-mode, I decided to keep the already present `ArmModeInstruction::Multiply` type and extending it a little with a `ArmModeMultiplyKind` to allow for a basic way of differentiating the opcodes.
Overflows are checked using `u64|u32::overflowing_mul(op1, op2)` which conveniently returns a tuple containing the mul result and whether an overflow occurred. I chose this way as it clearly shows the intent of what's happening there, perhaps we could only use such function when the `S` flag is set, otherwise there's really no point in using that. (It might bring extra overhead for no reason, but you guys tell me if that's any good to keep it like so).
Other than that, I don't really have anything important here to …
=> Arm: Implement mul opcodes (halfwords and non-halfwords)

emu/src/bus.rs, emu/src/cpu/arm/operations.rs, emu/src/cpu/arm7tdmi.rs, emu/src/cpu/thumb/operations.rs, emu/src/gba.rs, emu/src/memory/interrupts.rs, emu/src/render/ppu.rs, ui/src/cpu_handler.rs, ui/src/cpu_registers.rs, ui/src/disassembler.rs
The main idea of this change is to avoid having `Arc<Mutex<Bus>>` inside `Arm7tdmi` and have just a `Bus` instead.
Having an ArcMutex it was causing me some issues while working on interrupts implementation. Plus it's always been something I was not 100% sure about. I changed the `Gba` logic to hold only a reference to the cpu instead of both cpu and bus.
=> Avoid having `Arc<Mutex<Bus>>` inside `Arm7tdmi`

emu/src/bus.rs, emu/src/cpu/arm/operations.rs, emu/src/cpu/arm7tdmi.rs, emu/src/cpu/hardware/lcd.rs, emu/src/cpu/hardware/mod.rs, emu/src/cpu/mod.rs, emu/src/cpu/thumb/operations.rs, emu/src/memory/internal_memory.rs, emu/src/memory/mod.rs, emu/src/render/ppu.rs
The idea of this PR is to propose a new way to manage memory and hardware components.
Before we had everything under `InternalMemory` but every field was just containing registers.
This is not suitable now that we approach implementing the LCD since it has also its login instead of just a bunch of registers.
Also, having everything under `InternalMemory` was not "semantically" correct in my opinion, hardware components are external components to the CPU.
If we agree with this type of refactoring, we would also get rid of the `IORegister` struct which is useless at this point. I added it many months ago to try to handle read/write access through it but then we saw that it was not possible.
To manage read/write access we could do something like this:
- If the register is R/W, just make the …
=> Move `Lcd` out of `InternalMemory`

.github/workflows/rust.yml, Cargo.toml, README.md, emu/Cargo.toml, emu/src/bus.rs, emu/src/cpu/arm/instructions.rs, emu/src/cpu/arm/operations.rs, emu/src/cpu/arm7tdmi.rs, emu/src/cpu/thumb/instruction.rs, emu/src/render/color.rs, emu/src/render/ppu.rs, justfile, logger/Cargo.toml, logger/src/lib.rs, src/main.rs, ui/Cargo.toml, ui/src/app.rs, ui/src/disassembler.rs, ui/src/lib.rs, ui/src/palette_visualizer.rs, vecfixed/src/lib.rs
- Just: Remove useless cmds
- Just: Add quick cmd for run rom
- Logger: Make logger a feature opt-in
- Doc: Update README
- UI: Make disassambler a feature opt-in
Those are the 3 different perf with no feature, logger and disassembler
=> Create `logger` and `disassembler` feature default disabled

emu/src/bitwise.rs, emu/src/bus.rs, emu/src/cpu/arm/alu_instruction.rs, emu/src/cpu/arm/operations.rs, emu/src/cpu/arm7tdmi.rs, emu/src/cpu/thumb/mode.rs, emu/src/cpu/thumb/operations.rs, logger/src/lib.rs
In the `LoadAddress` Thumb instruction we were setting bit 0 to 0 while we should set bit 1 to zero, according to documentation.
I also did some small fixes around.
=> Fix `LoadAddress`

emu/src/bus.rs, emu/src/cpu/arm/operations.rs, emu/src/cpu/arm7tdmi.rs, emu/src/cpu/thumb/operations.rs
We were not aligning the address when reading/writing word.
Also, I noticed that when reading a misaligned address we should rotate the value so that the selected byte ends in bits 0-7 of the destination register.
Source:
We should do the same for ARM as well. But we can wait until we run the ARM tests
=> Fix memory align

emu/src/cpu/thumb/operations.rs
* Thumb: Correctly handles base in register list for multiple load/store
This commit fixes thumb tests 230,231,232.
* Thumb: Correctly emulates undefined behavior when register list is empty in block load/store
This should never happen but test rom has a test for it.
This commit fixes tests 227 and 229.
=> Fix blockmemory

emu/src/cpu/hardware/lcd.rs, emu/src/cpu/hardware/lcd/layers.rs, emu/src/cpu/hardware/lcd/layers/layer_0.rs, emu/src/cpu/hardware/lcd/layers/layer_1.rs, emu/src/cpu/hardware/lcd/layers/layer_2.rs, emu/src/cpu/hardware/lcd/layers/layer_3.rs, emu/src/cpu/hardware/lcd/layers/layer_obj.rs
Structs for other BG layers have been created as well (empty for now).
=> Lcd: Move Obj render logic to `LayerObj`

emu/src/cpu/arm7tdmi.rs, ui/src/cpu_handler.rs
As part of my re-onboarding process and to familiarise myself with the recent changes to the emulator, I spent some time exploring the UI and the underlying architecture. This Pull Request aims to enhance the controls related to CPU execution and debugging, providing a more user-friendly and informative experience.
- Display the current CPU cycle
- Restrict breakpoint address input to HEX ASCII
- Introduce a custom control to "step" CPU cycles
- Improve organisation of information using collapsible menus
=> UI: Improve CPU handler controls
